[project]
name = "github-data-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
    "tqdm>=4.67.3",
]
